language: node_js
node_js:
  - 8.9.4
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++-4.8
script:
  - npm run-script test-travis
notifications:
  irc:
    channels:
      - irc.esper.net#crafatar
    skip_join: true
env:
  - TRAVIS=true CXX=g++-4.8
services:
  - redis-server
cache:
  directories:
    - node_modules